version: '3.8'

services:
  web:
    build:
      context: .
    deploy:
      replicas: 2
    networks:
      - dockerdemo
  lb:
    image: nginx:latest
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
    - "8080:8080"
    networks:
      - dockerdemo

networks:
  dockerdemo:
