- name: Ansible Demo
  hosts: webhosts
  become: true
  become_user: root

  vars:
    azure_fs_password: '{{ lookup("env", "AZURE_FS_PASS") }}'

  tasks:

    - name: Ping hosts
      ansible.builtin.ping:
      tags:
      - install
      - remove

    - name: Install NGINX 
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: yes
      tags: install
      
    - name: Mount share
      ansible.builtin.script:
        cmd: ./script.sh '{{ azure_fs_password }}'
      tags: web_config

    - name: Copy index.html file 
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'
      tags: web_config


    - name: Start nginx
      ansible.builtin.service: 
        name: nginx
        state: started
        enabled: yes
      tags: install

    - name: Stop nginx
      ansible.builtin.service: 
        name: nginx
        state: stopped
      tags: remove

    - name: Remove NGINX
      ansible.builtin.apt:
        name: nginx
        state: absent
        autoremove: yes
        purge: true
      tags: remove    

      